### ISSUE TITLE
Display current turn information.

### ISSUE THREAD

**Issue by akulhalli** [JazzType/refactored-happiness#1]
Print which player's turn it currently is while the clients wait for their turn.
The display format must be as follows.
`>> Please wait your turn. It is Player <number>'s turn.`

This must be displayed for each client, except the client whose turn it currently is.
For that client, notification must be:
`>> Your move.`
Followed by the possible moves that player has.

**Comment by ashwinlokkur** [comment]
This can be done only when the synchronization is proper. As far as I noticed in the break, the sync is messed up. (ie any user can choose his plan of action at any time)
